services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build_x86_64:
  image: docker:stable
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

build_rpi:
  image: docker:stable
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:rpi . -f Dockerfile.rpi
    - docker push $CI_REGISTRY_IMAGE:rpi

build_windows:
  image: windows-docker:stable
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:rpi . -f Dockerfile.rpi
    - docker push $CI_REGISTRY_IMAGE:rpi
