variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build_x86_64:
  image: docker:stable
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

build_rpi:
  image: docker:stable
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:rpi . -f Dockerfile.rpi
    - docker push $CI_REGISTRY_IMAGE:rpi

build_windows:
  image: servercore:ltsc2019
  tags:
  - shared-windows
  - windows
  - windows-1809
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:windows . -f Dockerfile.windows
    - docker push $CI_REGISTRY_IMAGE:windows
