dist: trusty
env:
  global:
    - PREFIX=/tmp
    - GYP_DEFINES="target_arch=arm"
  matrix:
    - GYP_GENERATOR_OUTPUT=x86_64 GNARGS='is_debug=false rtc_use_h264=true ffmpeg_branding="Chrome" rtc_include_tests=false enable_nacl=false rtc_enable_protobuf=false'
    - GYP_GENERATOR_OUTPUT=arm GNARGS='is_debug=false rtc_use_h264=true ffmpeg_branding="Chrome" rtc_include_tests=false enable_nacl=false rtc_enable_protobuf=false is_clang=false target_cpu="arm" arm_float_abi=hard treat_warnings_as_errors=false' CROSS=arm-linux-gnueabihf- SYSROOT=${TRAVIS_BUILD_DIR}/../webrtc/src/build/linux/debian_jessie_arm-sysroot
addons:
  apt:
    packages:
    - git
before_install:
- pushd ..
# get toolchain need to build WebRTC
- git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
- export PATH=$PATH:$(pwd)/depot_tools
- git clone --depth 1 https://github.com/raspberrypi/tools.git rpi_tools
- export PATH=$PATH:$(pwd)/rpi_tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin
# get WebRTC
- mkdir webrtc
- pushd webrtc
- fetch --no-history --nohooks webrtc
# buid WebRTC
- gclient sync
- pushd src
- gn gen ${GNOUTPUT}/out/Release --args=${GNARGS}
- ninja -C ${GNOUTPUT}/out/Release
- popd
#
- popd
language: cpp
compiler:
- gcc
script:
- make PREFIX=${PREFIX} live555 all tgz
before_deploy:
- export RELEASE_X86_PKG_FILE=$(ls *_x86_64-linux*.tgz)
- echo "RELEASE_X86_PKG_FILE=${RELEASE_X86_PKG_FILE}"   
- export RELEASE_ARM_PKG_FILE=$(ls *_arm-linux*.tgz)
- echo "RELEASE_ARM_PKG_FILE=${RELEASE_ARM_PKG_FILE}"   
deploy:
- provider: heroku
  skip_cleanup: true
  api_key:
    secure: NmTNf38MkoWWQZrRkXyWqCdRRO4Xjv+Kl0TOZPw+qCXva4kc2T0uwSi2o4YNZBUA533NyZvO6IJMQOpx24UkjPhxVv591FBB+HdUevOxD4SEAE8fBibpHVX3sTU0XLp/mx+BpNFdxKrEHHzoyBZBFjesQVVMVczB4AOv/KZerGw=
  on:
    repo: mpromonet/webrtc-streamer
    tags: false
- provider: releases
  skip_cleanup: true
  api_key:
    secure: FMXzmhBmuy7Jou3h5lG10b8xl5oqI96aYoUrUHO2rfKqQ4UMKxT3hXcdxOnSsnbI6d8NfXbOPKqmqmD4vTk+EqQjCK9fmsNxAg1UktLIsuOxoWmEWYLK5d3xpIuRmfRQDtPVjcryrE420FCfZS67lyr22+v1pLcvcD61ebGZLCg=
  file: 
  - "${RELEASE_X86_PKG_FILE}"
  - "${RELEASE_ARM_PKG_FILE}"
  on:
    repo: mpromonet/webrtc-streamer
    tags: true
