dist: trusty
env:
  PREFIX=/tmp
addons:
  apt:
    packages:
    - git
before_install:
- pushd ..
# build live555
- wget http://www.live555.com/liveMedia/public/live555-latest.tar.gz -O - | tar xzf -
- pushd live
- ./genMakefiles linux
- make install PREFIX=${PREFIX}
- popd
# build WebRTC
- git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
- export PATH=$PATH:$(pwd)/depot_tools
- mkdir webrtc
- pushd webrtc
- fetch --no-history --nohooks webrtc
- gclient sync
- pushd src
- gn gen out/Release --args='is_debug=false rtc_use_h264=true ffmpeg_branding="Chrome" rtc_include_tests=false'
- ninja -C out/Release
- popd
- popd
#
- popd
language: cpp
compiler:
- gcc
script:
- make PREFIX=${PREFIX}
- make tgz
before_deploy:
- export RELEASE_PKG_FILE=$(ls *.tgz)
- echo "deploying ${RELEASE_PKG_FILE} to GitHub releases"    
deploy:
- provider: heroku
  skip_cleanup: true
  api_key:
    secure: KhZVpH3MqZxcarJMMku96twpNJw0qeXE8i5gz0hydR7i31NSUl4M69r8uRk6kBiVl7lm7kCTCONE+18cbqLKf1jc3pFV7y3nf178xY6St0NUbsjuYart1EAEwSlZMMw1cGy3Qd3YDn/xKG2+hpNbpW4MVyZ6abYtYt14rV/Pcoo=
  on:
    repo: mpromonet/webrtc-streamer
    tags: false
    
- provider: releases
  skip_cleanup: true
  api_key:
    secure: FMXzmhBmuy7Jou3h5lG10b8xl5oqI96aYoUrUHO2rfKqQ4UMKxT3hXcdxOnSsnbI6d8NfXbOPKqmqmD4vTk+EqQjCK9fmsNxAg1UktLIsuOxoWmEWYLK5d3xpIuRmfRQDtPVjcryrE420FCfZS67lyr22+v1pLcvcD61ebGZLCg=
  file: "${RELEASE_PKG_FILE}"
  on:
    repo: mpromonet/webrtc-streamer
    tags: true
