dist: trusty
env:
  global:
    - PREFIX=/tmp
    - GYP_DEFINES="target_arch=arm"
  matrix:
    - GYP_GENERATOR_OUTPUT=x86_64 GNARGS='is_debug=false rtc_use_h264=true ffmpeg_branding="Chrome" rtc_include_tests=false enable_nacl=false rtc_enable_protobuf=false use_custom_libcxx=false'
    - GYP_GENERATOR_OUTPUT=armv7 GNARGS='is_debug=false rtc_use_h264=true ffmpeg_branding="Chrome" rtc_include_tests=false enable_nacl=false rtc_enable_protobuf=false use_custom_libcxx=false is_clang=false target_cpu="arm" treat_warnings_as_errors=false' CROSS=arm-linux-gnueabihf- SYSROOT=${TRAVIS_BUILD_DIR}/../webrtc/src/build/linux/debian_jessie_arm-sysroot
    - GYP_GENERATOR_OUTPUT=armv6 GNARGS='is_debug=false rtc_include_tests=false enable_nacl=false rtc_enable_protobuf=false use_custom_libcxx=false is_clang=false target_cpu="arm" arm_version=6 arm_arch="armv6" arm_float_abi="hard" arm_use_neon=false arm_optionally_use_neon=false rtc_build_with_neon=false arm_use_thumb=false treat_warnings_as_errors=false rtc_include_opus=false' CROSS=arm-linux-gnueabihf- SYSROOT=${TRAVIS_BUILD_DIR}/../webrtc/src/build/linux/debian_jessie_arm-sysroot CFLAGS_EXTRA="-march=armv6 -mfpu=vfp -mfloat-abi=hard"
addons:
  apt:
    packages:
    - git
    - libasound2-dev
before_install:
- pushd ..
# get toolchain need to build WebRTC
- git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
- export PATH=$PATH:$(pwd)/depot_tools
- git clone --depth 1 https://github.com/raspberrypi/tools.git rpi_tools
- export PATH=$PATH:$(pwd)/rpi_tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin
# get WebRTC
- mkdir webrtc
- pushd webrtc
- fetch --no-history --nohooks webrtc
# buid WebRTC
- gclient sync
- pushd src
- gn gen ${GYP_GENERATOR_OUTPUT}/out/Release --args="${GNARGS}"
- ninja -C ${GYP_GENERATOR_OUTPUT}/out/Release webrtc
- popd
- popd
#
- popd
language: cpp
compiler:
- gcc
script:
- make PREFIX=${PREFIX} live555 
- make PREFIX=${PREFIX} all tgz
before_deploy:
- export RELEASE_PKG_FILE=$(ls *.tgz)
- echo "RELEASE_PKG_FILE=${RELEASE_PKG_FILE}"   
deploy:
- provider: heroku
  skip_cleanup: true
  api_key:
    secure: NmTNf38MkoWWQZrRkXyWqCdRRO4Xjv+Kl0TOZPw+qCXva4kc2T0uwSi2o4YNZBUA533NyZvO6IJMQOpx24UkjPhxVv591FBB+HdUevOxD4SEAE8fBibpHVX3sTU0XLp/mx+BpNFdxKrEHHzoyBZBFjesQVVMVczB4AOv/KZerGw=
  on:
    repo: mpromonet/webrtc-streamer
    tags: false
    condition: $GYP_GENERATOR_OUTPUT = x86_64
- provider: releases
  skip_cleanup: true
  api_key:
    secure: FMXzmhBmuy7Jou3h5lG10b8xl5oqI96aYoUrUHO2rfKqQ4UMKxT3hXcdxOnSsnbI6d8NfXbOPKqmqmD4vTk+EqQjCK9fmsNxAg1UktLIsuOxoWmEWYLK5d3xpIuRmfRQDtPVjcryrE420FCfZS67lyr22+v1pLcvcD61ebGZLCg=
  file: 
  - "${RELEASE_PKG_FILE}"
  on:
    repo: mpromonet/webrtc-streamer
    tags: true
