image: 
- Visual Studio 2017
- Ubuntu

platform: x64

configuration:
  - Release
  - Debug

environment:
  GNARGS_COMMON: rtc_use_h264=true ffmpeg_branding=""Chrome"" rtc_include_tests=false rtc_enable_protobuf=false use_custom_libcxx=false rtc_include_pulse_audio=false rtc_build_examples=false use_sysroot=false is_clang=false treat_warnings_as_errors=false

install:
  - cmd: set DEPOT_TOOLS_WIN_TOOLCHAIN=0
  - cmd: set PATH=%APPVEYOR_BUILD_FOLDER%\..\depot_tools;%PATH%
  - sh: export PATH=${APPVEYOR_BUILD_FOLDER}/../depot_tools:${PATH}
  - cmd: set GENERATOR="Visual Studio 15 2017 Win64"
  - sh: export GENERATOR="Unix Makefiles"
  - git submodule update --init
  - cd ..
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git 
  - mkdir webrtc
  - cd webrtc
  - fetch --no-history --nohooks webrtc 
  - cd src
  - ps: echo CONFIGURATION=$env:CONFIGURATION
  - ps: echo PLATFORM=$env:PLATFORM
  - ps: echo GENERATOR=$env:GENERATOR
  - ps: (get-content DEPS) | foreach-object {$_ -replace "'src/resources'],", "'src/resources'],'condition':'rtc_include_tests==true',"} | set-content DEPS
  - gclient sync
  - ps: if ($env:CONFIGURATION = "Release") { $env:GNARGS="is_debug=false" + " " + $env:GNARGS_COMMON } else { $env:GNARGS="is_debug=true" + " " + $env:GNARGS_COMMON }
  - ps: echo GNARGS=$env:GNARGS
  - ps: gn gen "out/$env:CONFIGURATION" --args="$env:GNARGS"
  - ps: ninja -C "out/$env:CONFIGURATION" jsoncpp rtc_json webrtc

before_build:
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - ps: cmake . -G "$env:GENERATOR" -DWEBRTCBUILD="$env:CONFIGURATION"

build_script:
  - cmd: msbuild INSTALL.vcxproj /p:Configuration=%CONFIGURATION% /p:Platform=%PLATFORM% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - sh: make

after_build:
  - ps: cpack -C $env:CONFIGURATION

artifacts:
  - path: webrtc-streamer*.tar.gz

deploy:
  provider: GitHub
  auth_token:
    secure: Ov3sAkiU1iRjAOc7GYaScSUujzhKiTCz/gZ4uQws2fTaNu8O5FUciAQk4uuGeiC7
  draft: false
  prerelease: false
  on:
    branch: master                 
    appveyor_repo_tag: true       

