version: 2
jobs:
  build_x86_64:
    working_directory: ~/webrtc-streamer
    docker:
      - image: heroku/heroku:16
    environment:
      GNARGSCOMMON: 'rtc_include_tests=false rtc_enable_protobuf=false use_custom_libcxx=false use_ozone=true rtc_include_pulse_audio=false rtc_build_examples=false' 
      GYP_GENERATOR_OUTPUT: "x86_64"
      GNARGS: 'is_debug=false rtc_use_h264=true ffmpeg_branding="Chrome"'      
      TAR_OPTIONS: --no-same-owner

    steps:
      - checkout
      
      - run: apt-get update; apt-get install -y --no-install-recommends autoconf automake libtool git make g++ xz-utils
      - run: git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git ${HOME}/depot_tools
      - run: echo 'export PATH=${HOME}/depot_tools:$PATH' >> $BASH_ENV
      - run: mkdir webrtc && cd webrtc && fetch --no-history --nohooks webrtc 
      - run: cd webrtc && sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" src/DEPS 
      - run: cd webrtc && gclient sync 
      - run: make WEBRTCROOT=${HOME}/webrtc live555 alsa-lib SYSROOT=${HOME}/webrtc/src/build/linux/debian_stretch_amd64-sysroot
      - run: cd webrtc/src && gn gen ${GYP_GENERATOR_OUTPUT}/out/Release --args="${GNARGSCOMMON} ${GNARGS}" && ninja -C ${GYP_GENERATOR_OUTPUT}/out/Release jsoncpp rtc_json webrtc 
      - run: make WEBRTCROOT=${HOME}/webrtc all tgz SYSROOT=${HOME}/webrtc/src/build/linux/debian_stretch_amd64-sysroot

      # archive artifacts
      - run: mkdir /distrib && cp *.tgz /distrib
      - store_artifacts:      
          path: /distrib  

      # deploy on heroku
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "9d:ef:66:ee:e1:95:2b:e6:98:05:01:ac:48:5c:53:be"
      - deploy:
          name: "Deploy to Heroku"
          command: git add -f webrtc-streamer && git commit -m 'force add for heroku deployement' && git push --force git@heroku.com:rtsp2webrtc.git HEAD:refs/heads/master

workflows:
  version: 2
  build:
    jobs:
      - build_x86_64

