  name: webrtc-streamer
  version: git
  summary: webrtc streamer
  description: webrtc streamer
  grade: devel 
  confinement: devmode
  base: core18
  architectures:
    - build-on: amd64
    - build-on: i386

  parts:
    webrtc:
      plugin: dump
      source: https://chromium.googlesource.com/chromium/tools/depot_tools.git
      source-type: git
      override-build: |
        cp -r ../src/* /usr/local/bin/
        mkdir /webrtc
        cd /webrtc
        fetch --no-history --nohooks webrtc
        sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" src/DEPS
        gclient sync

    webrtc-streamer:
      after: [webrtc]
      plugin: cmake
      source: .
      source-type: git
      configflags:
      - -DWEBRTCROOT=/webrtc
      build-packages:
      - curl
      - g++
      - make
      - python
      - pkg-config
      - libgtk-3-dev
      - libasound2-dev
      stage-packages:
      - libgtk-3-0
      - libasound2

  apps:
    webrtc-streamer:
      command: webrtc-streamer
      daemon: simple   
      plugs: [network-bind]
