name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: pkg
      run: sudo apt-get install -y --no-install-recommends g++ autoconf automake libtool xz-utils libasound2-dev libgtk-3-dev cmake p7zip-full
    - name: depot_tools
      run: git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
    - name: fetch webrtc
      run: |
          export PATH=$(pwd)/depot_tools:$PATH
          mkdir webrtc
          pushd webrtc
          fetch --no-history --nohooks webrtc
          sed -i -e "s|'src/resources'],|'src/resources'],'condition':'rtc_include_tests==true',|" src/DEPS 
          gclient sync 
          popd
    - name: cmake
      run: |
          export PATH=$(pwd)/depot_tools:$PATH
          cmake -DWEBRTCROOT=./webrtc -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .
    - name: make 
      run: | 
          g++ -v
          g++ -print-file-name=libstdc++.a
          nm $(g++ -print-file-name=libstdc++.a) | c++filt  | grep ::basic_ostringstream
          nm libwebrtcextra.a | c++filt | grep ::basic_ostringstream
          make VERBOSE=1
