name: C/C++ CI windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: depot_tools
      run: git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
    - name: fetch webrtc
      shell: cmd
      run: |
          set "PATH=%PATH%;%GITHUB_WORKSPACE%\depot_tools"
          git config --global core.autocrlf false 
          git config --global core.filemode false 
          mkdir webrtc
          pushd webrtc
          fetch --no-history webrtc
          popd
      env:
        DEPOT_TOOLS_WIN_TOOLCHAIN: 0
        CLANG_VERSION: ToT
        PYTHONIOENCODING: UTF-8
        GCLIENT_PY3: 1
    - name: cmake
      shell: cmd
      run: |
          set "PATH=%PATH%;%GITHUB_WORKSPACE%\depot_tools;%GITHUB_WORKSPACE%\webrtc\src\third_party\llvm-build\Release+Asserts\bin;%GITHUB_WORKSPACE%\webrtc\src\build\toolchain\win\rc\win"
          set
          cmake -G Ninja -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe -DWEBRTCROOT=./webrtc .
          ninja 
    - name: cpack 
      run: cpack       
