name: Node.js Package

on: [push]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              git submodule update --init
              git fetch --prune --unshallow --tags
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: "@mpromonet"
          always-auth: true
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm config ls -l        
      - run: |
              npm config set git-tag-version=false
              npm version $(git describe --tags --always)
              npm publish --access public
